---
title: "p8105_hw5_tc3326"
author: "KK Chen"
date: "2024-11-15"
output: github_document
---

```{r setup, include = FALSE, message = FALSE}
library(tidyverse)
library(ggplot2)
```

# Problem 2
### Set Parameters and Simulate Data
```{r}
simulate_t_test = function(true_mean, sample_size = 30, std_dev = 5) {
  simulated_data = tibble(sample_values = rnorm(sample_size, true_mean, std_dev))
  
  t_test_result = t.test(simulated_data$sample_values, mu = 0)
  cleaned_result = broom::tidy(t_test_result)
  
  result = tibble(
    sample_mean = cleaned_result$estimate,
    p_value = cleaned_result$p.value,
  )
  
  return(result)
}
```

```{r}
simulation_results_mu_0 = 
  tibble(iter = 1:5000) %>%
  mutate(simulation_output = map(iter, ~simulate_t_test(true_mean = 0))) %>%
  unnest(simulation_output)

simulation_results_mu_0
```

```{r}
true_mean_values = c(1, 2, 3, 4, 5, 6)

sim_res_multiple_means = 
  expand_grid(
    true_mean = true_mean_values,
    iter = 1:5000 ) %>%
  mutate(simulation_output = map(true_mean, ~simulate_t_test(true_mean = .x))) %>%
  unnest(simulation_output, names_sep = "_")

sim_res_multiple_means
```








